### ISSUE TITLE
运行问题请教

### ISSUE THREAD

**Issue by xl232lx** [Forrest-110/FastMAC#4]
作者您好，再次打扰您，请教一下
1、我运行python extract_corr.py出现/home/xialei/FastMAC/pipeline_SLAM/thirdparty/GeoTransformer/geotransformer/modules/geotransformer/superpoint_matching.py:44: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  ref_sel_indices = corr_indices // matching_scores.shape[1]
和
Traceback (most recent call last):
  File "extract_corr.py", line 516, in <module>
    corr_extractor.extract_corr(src_points, ref_points)
  File "extract_corr.py", line 499, in extract_corr
    output_dict = self.model(data_dict)
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "extract_corr.py", line 224, in forward
    _, ref_node_masks, ref_node_knn_indices, ref_node_knn_masks = point_to_node_partition(
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xialei/FastMAC/pipeline_SLAM/thirdparty/GeoTransformer/geotransformer/modules/ops/pointcloud_partition.py", line 95, in point_to_node_partition
    node_knn_indices = sq_dist_mat.topk(k=point_limit, dim=1, largest=False)[1]  # (M, K)
RuntimeError: selected index k out of range
的打印；
2、运行python pipeline.py 出现/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py:90: RuntimeWarning: invalid value encountered in scalar divide
  wnew = int(w * dpi / n) * n / dpi
/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py:91: RuntimeWarning: invalid value encountered in scalar divide
  hnew = int(h * dpi / n) * n / dpi
Traceback (most recent call last):
  File "pipeline.py", line 79, in <module>
    with writer.saving(fig, video_name, num_frames_to_save):
  File "/root/anaconda3/envs/fastmac/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py", line 231, in saving
    self.setup(fig, outfile, dpi, *args, **kwargs)
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py", line 317, in setup
    self._w, self._h = self._adjust_frame_size()
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py", line 304, in _adjust_frame_size
    w, h = adjusted_figsize(wo, ho, self.dpi, 2)
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py", line 92, in adjusted_figsize
    return correct_roundoff(wnew, dpi, n), correct_roundoff(hnew, dpi, n)
  File "/root/anaconda3/envs/fastmac/lib/python3.8/site-packages/matplotlib/animation.py", line 83, in correct_roundoff
    if int(x*dpi) % n != 0:
ValueError: cannot convert float NaN to integer
打印，请问这是我输入的点云有问题么？劳烦您帮忙看一下，万分感谢！！！

**Comment by Forrest-110** [comment]
这两个报错是否是同一次运行？第一个报错是geotransformer无法提取输入点云的correspondence，有可能是输入点云的问题。第二个报错是因为wnew = int(w * dpi / n) * n / dpi中n或dpi=0，请检查这两个值的value

**Comment by xl232lx** [comment]
您好，两个报错是同一次运行，数据集取自KITTI，然后我换了别的数据集运行python extract_corr.py出现的另外一个报错
